version: 2
updates:
  # Track GitHub Actions versions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    auto-merge:
      enabled: true
      auto-merge-type: squash
      auto-commit-message: "chore: auto-update github actions"
