"""Scanner extraction package - consolidates variable, task, and data extraction logic.

Exports public API for variable discovery orchestation and task feature extraction.
"""

from __future__ import annotations

# Task parsing constants and functions
from .task_parser import (
    TASK_INCLUDE_KEYS,
    ROLE_INCLUDE_KEYS,
    INCLUDE_VARS_KEYS,
    SET_FACT_KEYS,
    TASK_BLOCK_KEYS,
    TASK_META_KEYS,
    ROLE_NOTES_RE,
    ROLE_NOTES_SHORT_RE,
    TASK_NOTES_LONG_RE,
    TASK_NOTES_SHORT_RE,
    COMMENT_CONTINUATION_RE,
    _iter_task_include_targets,
    _iter_task_mappings,
    _is_path_excluded,
    _load_yaml_file,
    _collect_task_files,
    _format_inline_yaml,
    _normalize_exclude_patterns,
    _is_relpath_excluded,
    _resolve_task_include,
    _extract_role_notes_from_comments,
    _split_task_annotation_label,
    _extract_task_annotations_for_file,
    _task_anchor,
    _detect_task_module,
    _extract_collection_from_module_name,
    _compact_task_parameters,
    _collect_unconstrained_dynamic_role_includes,
    _collect_unconstrained_dynamic_task_includes,
    _collect_task_handler_catalog,
    _collect_molecule_scenarios,
    extract_role_features,
)

# Variable extraction functions
from .variable_extractor import (
    DEFAULT_TARGET_RE,
    JINJA_VAR_RE,
    JINJA_IDENTIFIER_RE,
    VAULT_KEY_RE,
    IGNORED_IDENTIFIERS,
    _SECRET_NAME_TOKENS,
    _VAULT_MARKERS,
    _CREDENTIAL_PREFIXES,
    _URL_PREFIXES,
    _collect_include_vars_files,
    _collect_set_fact_names,
    _collect_register_names,
    _find_variable_line_in_yaml,
    _collect_referenced_variable_names,
    _infer_variable_type,
    _is_sensitive_variable,
    _looks_secret_name,
    _looks_secret_value,
    _resembles_password_like,
    _extract_default_target_var,
    _collect_dynamic_include_vars_refs,
    _collect_dynamic_task_include_refs,
    _read_seed_yaml,
    _resolve_seed_var_files,
    load_seed_variables,
    _refresh_policy_derived_state,
)

# Discovery helpers
from .discovery import (
    iter_role_variable_map_candidates,
    load_meta,
    load_requirements,
    load_variables,
    resolve_scan_identity,
)

# Data loading functions
from .dataload import (
    iter_role_yaml_candidates,
    parse_yaml_candidate,
    collect_yaml_parse_failures,
    load_role_variable_maps,
    iter_role_argument_spec_entries,
    map_argument_spec_type,
)

# Requirements functions
from .requirements import (
    format_requirement_line,
    normalize_requirements,
    normalize_meta_role_dependencies,
    normalize_included_role_dependencies,
    extract_declared_collections_from_meta,
    extract_declared_collections_from_requirements,
    build_collection_compliance_notes,
    build_requirements_display,
)

__all__ = [
    # Task parsing
    "TASK_INCLUDE_KEYS",
    "ROLE_INCLUDE_KEYS",
    "INCLUDE_VARS_KEYS",
    "SET_FACT_KEYS",
    "TASK_BLOCK_KEYS",
    "TASK_META_KEYS",
    "ROLE_NOTES_RE",
    "ROLE_NOTES_SHORT_RE",
    "TASK_NOTES_LONG_RE",
    "TASK_NOTES_SHORT_RE",
    "COMMENT_CONTINUATION_RE",
    "_iter_task_include_targets",
    "_iter_task_mappings",
    "_is_path_excluded",
    "_load_yaml_file",
    "_collect_task_files",
    "_format_inline_yaml",
    "_normalize_exclude_patterns",
    "_is_relpath_excluded",
    "_resolve_task_include",
    "_extract_role_notes_from_comments",
    "_split_task_annotation_label",
    "_extract_task_annotations_for_file",
    "_task_anchor",
    "_detect_task_module",
    "_extract_collection_from_module_name",
    "_compact_task_parameters",
    "_collect_unconstrained_dynamic_role_includes",
    "_collect_unconstrained_dynamic_task_includes",
    "_collect_task_handler_catalog",
    "_collect_molecule_scenarios",
    "extract_role_features",
    # Variables
    "DEFAULT_TARGET_RE",
    "JINJA_VAR_RE",
    "JINJA_IDENTIFIER_RE",
    "VAULT_KEY_RE",
    "IGNORED_IDENTIFIERS",
    "_SECRET_NAME_TOKENS",
    "_VAULT_MARKERS",
    "_CREDENTIAL_PREFIXES",
    "_URL_PREFIXES",
    "_collect_include_vars_files",
    "_collect_set_fact_names",
    "_collect_register_names",
    "_find_variable_line_in_yaml",
    "_collect_referenced_variable_names",
    "_infer_variable_type",
    "_is_sensitive_variable",
    "_looks_secret_name",
    "_looks_secret_value",
    "_resembles_password_like",
    "_extract_default_target_var",
    "_collect_dynamic_include_vars_refs",
    "_collect_dynamic_task_include_refs",
    "_read_seed_yaml",
    "_resolve_seed_var_files",
    "load_seed_variables",
    "_refresh_policy_derived_state",
    # Discovery
    "iter_role_variable_map_candidates",
    "load_meta",
    "load_requirements",
    "load_variables",
    "resolve_scan_identity",
    # Data loading
    "iter_role_yaml_candidates",
    "parse_yaml_candidate",
    "collect_yaml_parse_failures",
    "load_role_variable_maps",
    "iter_role_argument_spec_entries",
    "map_argument_spec_type",
    # Requirements
    "format_requirement_line",
    "normalize_requirements",
    "normalize_meta_role_dependencies",
    "normalize_included_role_dependencies",
    "extract_declared_collections_from_meta",
    "extract_declared_collections_from_requirements",
    "build_collection_compliance_notes",
    "build_requirements_display",
]
