"""Ansible-specific error codes and taxonomy.

Defines error code constants used throughout the Ansible plugin layer
for structured error envelope construction and categorization.
"""

from __future__ import annotations

# Ansible error code constants
# Format: ANSIBLE_[DOMAIN]_[CONDITION]

# Module execution errors
ANSIBLE_MODULE_NOT_FOUND = "ANSIBLE_MODULE_NOT_FOUND"
ANSIBLE_MODULE_LOAD_ERROR = "ANSIBLE_MODULE_LOAD_ERROR"
ANSIBLE_TASK_FAILED = "ANSIBLE_TASK_FAILED"
ANSIBLE_TASK_TIMEOUT = "ANSIBLE_TASK_TIMEOUT"
ANSIBLE_HANDLER_FAILED = "ANSIBLE_HANDLER_FAILED"

# Syntax and parsing errors
ANSIBLE_SYNTAX_ERROR = "ANSIBLE_SYNTAX_ERROR"
ANSIBLE_YAML_PARSE_ERROR = "ANSIBLE_YAML_PARSE_ERROR"
ANSIBLE_TASK_VALIDATION_ERROR = "ANSIBLE_TASK_VALIDATION_ERROR"

# Collection and import errors
ANSIBLE_COLLECTION_NOT_FOUND = "ANSIBLE_COLLECTION_NOT_FOUND"
ANSIBLE_COLLECTION_VERSION_MISMATCH = "ANSIBLE_COLLECTION_VERSION_MISMATCH"
ANSIBLE_ROLE_NOT_FOUND = "ANSIBLE_ROLE_NOT_FOUND"

# File and I/O errors
ANSIBLE_ROLE_FILE_NOT_FOUND = "ANSIBLE_ROLE_FILE_NOT_FOUND"
ANSIBLE_TASK_FILE_NOT_FOUND = "ANSIBLE_TASK_FILE_NOT_FOUND"
ANSIBLE_INVENTORY_FILE_NOT_FOUND = "ANSIBLE_INVENTORY_FILE_NOT_FOUND"
ANSIBLE_VAR_FILE_NOT_FOUND = "ANSIBLE_VAR_FILE_NOT_FOUND"

# Authentication and authorization errors
ANSIBLE_AUTH_ERROR = "ANSIBLE_AUTH_ERROR"
ANSIBLE_PERMISSION_DENIED = "ANSIBLE_PERMISSION_DENIED"
ANSIBLE_CREDENTIAL_ERROR = "ANSIBLE_CREDENTIAL_ERROR"

# Network and connectivity errors
ANSIBLE_CONNECTION_TIMEOUT = "ANSIBLE_CONNECTION_TIMEOUT"
ANSIBLE_CONNECTION_ERROR = "ANSIBLE_CONNECTION_ERROR"
ANSIBLE_HOST_UNREACHABLE = "ANSIBLE_HOST_UNREACHABLE"

# Variable and fact errors
ANSIBLE_VARIABLE_UNDEFINED = "ANSIBLE_VARIABLE_UNDEFINED"
ANSIBLE_FACT_NOT_FOUND = "ANSIBLE_FACT_NOT_FOUND"
ANSIBLE_LOOP_ERROR = "ANSIBLE_LOOP_ERROR"

# Dictionary of all Ansible error codes for reference
ANSIBLE_ERROR_CODES = {
    # Module execution
    ANSIBLE_MODULE_NOT_FOUND,
    ANSIBLE_MODULE_LOAD_ERROR,
    ANSIBLE_TASK_FAILED,
    ANSIBLE_TASK_TIMEOUT,
    ANSIBLE_HANDLER_FAILED,
    # Syntax and parsing
    ANSIBLE_SYNTAX_ERROR,
    ANSIBLE_YAML_PARSE_ERROR,
    ANSIBLE_TASK_VALIDATION_ERROR,
    # Collection and imports
    ANSIBLE_COLLECTION_NOT_FOUND,
    ANSIBLE_COLLECTION_VERSION_MISMATCH,
    ANSIBLE_ROLE_NOT_FOUND,
    # File and I/O
    ANSIBLE_ROLE_FILE_NOT_FOUND,
    ANSIBLE_TASK_FILE_NOT_FOUND,
    ANSIBLE_INVENTORY_FILE_NOT_FOUND,
    ANSIBLE_VAR_FILE_NOT_FOUND,
    # Auth
    ANSIBLE_AUTH_ERROR,
    ANSIBLE_PERMISSION_DENIED,
    ANSIBLE_CREDENTIAL_ERROR,
    # Network
    ANSIBLE_CONNECTION_TIMEOUT,
    ANSIBLE_CONNECTION_ERROR,
    ANSIBLE_HOST_UNREACHABLE,
    # Variables
    ANSIBLE_VARIABLE_UNDEFINED,
    ANSIBLE_FACT_NOT_FOUND,
    ANSIBLE_LOOP_ERROR,
}
