"""Scanner data contracts, builders, and types.

This module consolidates all TypedDict data contracts used throughout the scanner
pipeline, providing a single source of truth for data structure definitions.
It also exports builder classes for fluent, type-safe construction of immutable data.
"""

from .contracts_output import ScanPayloadBuilder as ScanPayloadBuilder
from .contracts_variables import VariableRowBuilder as VariableRowBuilder
from .contracts import (
    AnnotationQualityCounters as AnnotationQualityCounters,
    CollectionScanResult as CollectionScanResult,
    EmitScanOutputsArgs as EmitScanOutputsArgs,
    FailureDetail as FailureDetail,
    FailurePolicyContract as FailurePolicyContract,
    FeaturesContext as FeaturesContext,
    FinalOutputPayload as FinalOutputPayload,
    NormalizedScannerReportMetadata as NormalizedScannerReportMetadata,
    OutputConfiguration as OutputConfiguration,
    ReadmeSectionRenderInput as ReadmeSectionRenderInput,
    ReferenceContext as ReferenceContext,
    RepoScanResult as RepoScanResult,
    ReportRenderingMetadata as ReportRenderingMetadata,
    RoleScanResult as RoleScanResult,
    RunbookSidecarPayload as RunbookSidecarPayload,
    RunbookSidecarArgs as RunbookSidecarArgs,
    RunScanOutputPayload as RunScanOutputPayload,
    ScanRenderPayload as ScanRenderPayload,
    ScanBaseContext as ScanBaseContext,
    ScanContext as ScanContext,
    ScanContextPayload as ScanContextPayload,
    ScanMetadata as ScanMetadata,
    ScanOptionsDict as ScanOptionsDict,
    ScanPhaseError as ScanPhaseError,
    ScanPhaseStatus as ScanPhaseStatus,
    ScanReportSidecarArgs as ScanReportSidecarArgs,
    ScannerCounters as ScannerCounters,
    ScannerReportIssueListRow as ScannerReportIssueListRow,
    ScannerReportMetadata as ScannerReportMetadata,
    ScannerReportSectionRenderInput as ScannerReportSectionRenderInput,
    ScannerReportYamlParseFailureRow as ScannerReportYamlParseFailureRow,
    SectionBodyRenderResult as SectionBodyRenderResult,
    StyleGuideConfig as StyleGuideConfig,
    Variable as Variable,
    VariableAnalysisResults as VariableAnalysisResults,
    VariableProvenance as VariableProvenance,
    VariableRow as VariableRow,
    VariableRowWithMeta as VariableRowWithMeta,
    _StyleSection as _StyleSection,
    _SectionTitleBucket as _SectionTitleBucket,
)

__all__ = [
    "AnnotationQualityCounters",
    "CollectionScanResult",
    "EmitScanOutputsArgs",
    "FailureDetail",
    "FailurePolicyContract",
    "FeaturesContext",
    "FinalOutputPayload",
    "NormalizedScannerReportMetadata",
    "OutputConfiguration",
    "ReadmeSectionRenderInput",
    "ReferenceContext",
    "RepoScanResult",
    "ReportRenderingMetadata",
    "RoleScanResult",
    "RunbookSidecarPayload",
    "RunbookSidecarArgs",
    "RunScanOutputPayload",
    "ScanPayloadBuilder",
    "ScanRenderPayload",
    "ScanBaseContext",
    "ScanContext",
    "ScanContextPayload",
    "ScanMetadata",
    "ScanOptionsDict",
    "ScanPhaseError",
    "ScanPhaseStatus",
    "ScanReportSidecarArgs",
    "ScannerCounters",
    "ScannerReportIssueListRow",
    "ScannerReportMetadata",
    "ScannerReportSectionRenderInput",
    "ScannerReportYamlParseFailureRow",
    "SectionBodyRenderResult",
    "StyleGuideConfig",
    "Variable",
    "VariableAnalysisResults",
    "VariableProvenance",
    "VariableRow",
    "VariableRowBuilder",
    "VariableRowWithMeta",
]
