"""Feedback integration from prism-learn for guided audit recommendations.

This module defines the interface and schema for prism-learn feedback that guides
scanner behavior and output rendering. It's designed to be generated asynchronously
by prism-learn analyzing role metadata aggregates across many scans, or fetched
live from a prism-learn API endpoint.

See docs/FEEDBACK_INTEGRATION.md for schema and integration guide.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, TypedDict
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen


class FeedbackRecommendation(TypedDict, total=False):
    """A single recommendation learned from aggregate role analysis."""

    type: str
    """Recommendation category: check_collection_compliance, variable_detection, etc."""

    display: bool
    """Whether to display this audit in rendered output."""

    reason: str
    """Human-readable explanation of why this is recommended."""

    severity: str
    """Optional severity level: high, medium, low."""

    additional_data: dict[str, Any]
    """Optional extra context for implementation."""


class FeedbackDefectCategory(TypedDict, total=False):
    """Aggregate statistics for a defect category."""

    severity: str
    """high, medium, low."""

    count: int
    """How many roles exhibit this defect pattern."""

    description: str
    """Human-readable summary."""

    percentage: float
    """Percentage of analyzed roles."""


class FeedbackPayload(TypedDict, total=False):
    """Complete prism-learn feedback payload for guiding prism behavior.

    Generated by prism-learn after analyzing role metadata aggregates.
    Provides recommendations to improve documentation quality and consistency.
    """

    version: str
    """Feedback schema version (e.g., '1.0'). For future compatibility."""

    generated_at: str
    """ISO 8601 timestamp when feedback was generated."""

    analysis_window: dict[str, str]
    """Metadata: date_start, date_end, roles_analyzed, etc."""

    defect_categories: dict[str, FeedbackDefectCategory]
    """Aggregate statistics of defect patterns found."""

    recommendations: list[FeedbackRecommendation]
    """Ordered list of recommended scanner behavior changes."""

    summary: str
    """Human-readable executive summary of findings."""


def load_feedback(feedback_source: str | None) -> FeedbackPayload | None:
    """Load and validate feedback.json from prism-learn.

    Supports both local files and live HTTP/HTTPS API endpoints.

    Args:
        feedback_source: Path to local feedback.json file, HTTP(S) URL to API endpoint,
                        or None to skip loading.
                        Examples:
                        - /path/to/feedback.json (local file)
                        - https://prism-learn.example.com/api/feedback?role=my_role (API)

    Returns:
        Parsed feedback payload, or None if not provided.

    Raises:
        FileNotFoundError: If local file path provided but not found.
        URLError: If HTTP request fails (connection, timeout, etc).
        HTTPError: If HTTP request returns 4xx/5xx status.
        json.JSONDecodeError: If response JSON is malformed.
        ValueError: If feedback payload is invalid.
    """
    if not feedback_source:
        return None

    # Detect if source is a URL or local file
    is_url = feedback_source.startswith(("http://", "https://"))

    if is_url:
        # Fetch from API endpoint
        try:
            req = Request(feedback_source, headers={"Accept": "application/json"})
            with urlopen(req, timeout=10) as response:
                feedback_data = response.read().decode("utf-8")
        except HTTPError as exc:
            raise HTTPError(
                exc.url, exc.code, f"prism-learn API returned {exc.code}", exc.hdrs, exc.fp
            ) from exc
        except URLError as exc:
            raise URLError(f"failed to fetch feedback from {feedback_source}: {exc}") from exc
    else:
        # Load from local file
        path = Path(feedback_source)
        if not path.is_file():
            raise FileNotFoundError(f"feedback file not found: {feedback_source}")
        try:
            feedback_data = path.read_text(encoding="utf-8")
        except OSError as exc:
            raise FileNotFoundError(f"failed to read feedback file: {feedback_source}") from exc

    # Parse JSON
    try:
        feedback_dict = json.loads(feedback_data)
    except json.JSONDecodeError as exc:
        raise json.JSONDecodeError(
            f"invalid JSON in feedback response from {feedback_source}", exc.doc, exc.pos
        ) from exc

    if not isinstance(feedback_dict, dict):
        raise ValueError("feedback payload must be a JSON object")

    # Validate required fields for Phase 2+ implementation
    # For now, accept any dict to remain flexible
    return feedback_dict  # type: ignore


def apply_feedback_recommendations(
    feedback: FeedbackPayload | None,
    include_collection_checks: bool,
) -> dict[str, Any]:
    """Apply feedback recommendations to scanner behavior.

    Args:
        feedback: Parsed feedback payload from prism-learn, or None.
        include_collection_checks: Current CLI flag value.

    Returns:
        Dictionary of applied settings:
        - include_collection_checks: bool (may be overridden by feedback)
        - recommendations_applied: list[str] (which recommendations were acted on)

    Note:
        Phase 2+ will expand this to override more settings based on feedback.
        Currently documents the interface for future implementation.
    """
    settings = {
        "include_collection_checks": include_collection_checks,
        "recommendations_applied": [],
    }

    if not feedback:
        return settings

    # Phase 2+: Iterate through feedback["recommendations"] and apply changes
    # Example (not yet implemented):
    #   for rec in feedback.get("recommendations", []):
    #       if rec["type"] == "check_collection_compliance":
    #           settings["include_collection_checks"] = rec.get("display", False)
    #           settings["recommendations_applied"].append(rec["type"])

    return settings


__all__ = [
    "FeedbackPayload",
    "FeedbackRecommendation",
    "FeedbackDefectCategory",
    "load_feedback",
    "apply_feedback_recommendations",
]
